### ISSUE TITLE
Remove artifact from import from FEUDAL Adapter

### ISSUE THREAD

**Issue by joshuabach** [KIT-SCC/aarc-g002-entitlement#1]
This is very [feudal_adapter_ldf](https://git.scc.kit.edu/feudal/feudalAdapterLdf) specific:

https://github.com/KIT-SCC/aarc-g002-entitlement/blob/8582e37cb198ee3c55a9eba9d8ddf8ec60141f37/aarc_g002_entitlement/aarc_g002_entitlement.py#L15-L23

Should probly be updated.

**Comment by marcvs** [comment]
Was fixed by PR #3
