### ISSUE TITLE
use urn encoding for statements

### ISSUE THREAD

**Issue by marcvs** [KIT-SCC/aarc-g002-entitlement#2]
groups that contain characters such as : will have that url-encoded. Therefore group entries need be url-decoded for comparison

**Comment by msalle** [comment]
actually percent encoded, since the whole entitlement is a URN.
See https://tools.ietf.org/html/rfc8141#section-2 and https://tools.ietf.org/html/rfc3986#section-2.1 (note that the hyperlink to the latter in the former mistakenly points to the wrong section 2.1).
