### ISSUE TITLE
Handle non-g002 entitlements

### ISSUE THREAD

**Issue by lburgey** [KIT-SCC/aarc-g002-entitlement#4]
In #3 i removed the possibility of instantiating Aarc_g002_entitlement with a non-g002 entitlement.
From my POV the "handling" was largely undefined (or at least undocumented) anyway.

So: How should we handle non-g002 entitlements?

**Comment by marcvs** [comment]
Prime target is ease of use. Originally, I thought is_contained_in "handles" errors by returning "False" in case s.th. is wrong.
Probably raising a ValueError in case the constructor cannot construct an object is the right thing to do.
Could you add code for that into the Readme.md into the example?

**Comment by lburgey** [comment]
In #5 I added handling of non-g002-ents in this fashion:
Add a force parameter, if set to false, ignore if the entitlement is non-G002. All comparisions are done with the raw entitlement string.

**Comment by marcvs** [comment]
I'm not entirely sure, but I have the feeling that this is what I introduced the `strict` for. Checking;

**Comment by marcvs** [comment]
I was wrong. Strict was for g002-ish statements, used when creating a new statement for comparision
